baseurl = "/"
title = "WestGrid Autumn School 2020"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "manni"   # Chroma Style Gallery https://xyproto.github.io/splash/docs/longer/all.html

[params]
    author = "WestGrid"
    description = ""
    keywords = ""
    info = "Autumn School 2020"
    wgavatar = "/images/wglogo.png"
    favicon_32 = "/images/favicon.png"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Bash"
            weight = 1
            url = "bash-menu"

            [[languages.en.menu.main]]
            name = "Git"
            weight = 2
            url = "git"

            [[languages.en.menu.main]]
            name = "HPC"
            weight = 3
            url = "hpc-menu"

            [[languages.en.menu.main]]
            name = "Python"
            weight = 4
            url = "python-menu"

	    [[languages.en.menu.main]]
	    name = "PyTorch"
	    weight = 5
	    url  = "pytorch"

	    [[languages.en.menu.main]]
	    name = "Chapel"
	    weight = 6
	    url  = "chapel-menu"

	    [[languages.en.menu.main]]
	    name = "Julia"
	    weight = 7
	    url  = "julia"

	    [[languages.en.menu.main]]
	    name = "SciVis"
	    weight = 8
	    url  = "vis-menu"
